### ISSUE TITLE
Can convert numpy.int32, but not numpy.int64 type

### ISSUE THREAD

**Issue by endolith** [fredrik-johansson/mpmath#291]
```
mp.polyroots([1,2,3])
Out[327]: [mpc(real='-1.0', imag='-1.4142132'), mpc(real='-1.0', imag='1.4142132')]

mp.polyroots(array([1,2,3]))
Out[328]: [mpc(real='-1.0', imag='-1.4142132'), mpc(real='-1.0', imag='1.4142132')]

mp.polyroots(array([1,2,3],dtype='int64'))
Traceback (most recent call last):

  File "<ipython-input-329-12656ac1df15>", line 1, in <module>
    mp.polyroots(array([1,2,3],dtype='int64'))

  File "C:\Python27\lib\site-packages\mpmath\calculus\polynomials.py", line 151, in polyroots
    lead = ctx.convert(coeffs[0])

  File "C:\Python27\lib\site-packages\mpmath\ctx_mp_python.py", line 662, in convert
    return ctx._convert_fallback(x, strings)

  File "C:\Python27\lib\site-packages\mpmath\ctx_mp.py", line 561, in _convert_fallback
    raise TypeError("cannot create mpf from " + repr(x))

TypeError: cannot create mpf from 1
```

Maybe it can internally convert to a list of long ints first?

**Comment by fredrik-johansson** [comment]
Fixed.
