### ISSUE TITLE
Infinite loop in MDNewton solver

### ISSUE THREAD

**Issue by bohdantan** [fredrik-johansson/mpmath#327]
```
import mpmath

def eqs(n, z):
    eq1 = mpmath.fdiv(mpmath.polylog(n-1, z), mpmath.polylog(n, z)) - 2.4193548387096775
    eq2 = mpmath.fdiv(-mpmath.diff(lambda v: mpmath.polylog(v, z), n), mpmath.polylog(n, z)) - 0.29724937807346691
    return (eq1, eq2)

x0 = (0.1, 0.44932896411722156)

mpmath.findroot(eqs, x0)
```
`mpmath.findroot` never ends for specified function and starting point.
Problem is in loop https://github.com/fredrik-johansson/mpmath/blob/master/mpmath/calculus/optimization.py#L666

**Comment by skirpichev** [comment]
@bohdantan, I got on your example
```
>>> import mpmath
... 
... def eqs(n, z):
...     eq1 = mpmath.fdiv(mpmath.polylog(n-1, z), mpmath.polylog(n, z)) - 2.4193548387096775
...     eq2 = mpmath.fdiv(-mpmath.diff(lambda v: mpmath.polylog(v, z), n), mpmath.polylog(n, z)) - 0.29724937807346691
...     return (eq1, eq2)
... 
... x0 = (0.1, 0.44932896411722156)
... 
... mpmath.findroot(eqs, x0, verbose=True)
... 
Jx:
[ -0.58231632252864073962  3.03872169645910616964]
[-0.272579053445952013135  1.29596880912504275329]
s: [16.1677492644406650503]
[3.31661318672120284387]
Traceback (most recent call last):
  File "<python-input-0>", line 10, in <module>
    mpmath.findroot(eqs, x0, verbose=True)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/calculus/optimization.py", line 967, in findroot
    for x, error in iterations:
                    ^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/calculus/optimization.py", line 671, in __iter__
    fx = self.ctx.matrix(f(*x1))
                         ~^^^^^
  File "<python-input-0>", line 4, in eqs
    eq1 = mpmath.fdiv(mpmath.polylog(n-1, z), mpmath.polylog(n, z)) - 2.4193548387096775
                      ~~~~~~~~~~~~~~^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 1105, in f_wrapped
    retval = f(ctx, *args, **kwargs)
  File "/home/sk/src/mpmath/mpmath/functions/zeta.py", line 498, in polylog
    return polylog_general(ctx, s, z)
  File "/home/sk/src/mpmath/mpmath/functions/zeta.py", line 474, in polylog_general
    r = ctx.gamma(1-s)*(-u)**(s-1) + v
                       ~~~~^^~~~~~
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 328, in __pow__
    val = mpf_pow(sval, tval, prec, rounding)
  File "/home/sk/src/mpmath/mpmath/libmp/libelefun.py", line 316, in mpf_pow
    raise ComplexResult("negative number raised to a fractional power")
mpmath.libmp.libmpf.ComplexResult: negative number raised to a fractional power
```
