### ISSUE TITLE
mpmath and python 3.7

### ISSUE THREAD

**Issue by grozin** [fredrik-johansson/mpmath#407]
In python 3.7, when StopIteration is raised in an iterator, it produces
RuntimeError: generator raised StopIteration
see https://www.python.org/dev/peps/pep-0479/

Running tests with python 3.7 produces
_______________________________________________ [doctest] mpmath.ctx_fp.FPContext.qfac _______________________________________________
EXAMPLE LOCATION UNKNOWN, not showing all tests of that example
??? >>> qfac(4,3)
UNEXPECTED EXCEPTION: RuntimeError('generator raised StopIteration')
Traceback (most recent call last):

  File "/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/functions/qfunctions.py", line 126, in factors
    raise StopIteration

StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest mpmath.ctx_fp.FPContext.qfac[3]>", line 1, in <module>

  File "/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/ctx_mp_python.py", line 1016, in f_wrapped
    retval = f(ctx, *args, **kwargs)

  File "/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/functions/qfunctions.py", line 201, in qfac
    return ctx.qp(q, q, n, **kwargs) / (1-q)**n

  File "/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/functions/qfunctions.py", line 129, in qp
    return ctx.mul_accurately(factors)

  File "/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/ctx_base.py", line 391, in mul_accurately
    for factor in factors():

RuntimeError: generator raised StopIteration

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/ctx_fp.py:None: UnexpectedException
__________________________________________________________ test_qfunctions ___________________________________________________________

    def factors():
        k = 0
        r = ctx.one
        while 1:
            yield 1 - a*r
            r *= q
            k += 1
            if k >= n:
>               raise StopIteration
E               StopIteration

mpmath/functions/qfunctions.py:126: StopIteration

The above exception was the direct cause of the following exception:

    def test_qfunctions():
        mp.dps = 15
>       assert qp(2,3,100).ae('2.7291482267247332183e2391')

mpmath/tests/test_functions2.py:1449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mpmath/functions/qfunctions.py:129: in qp
    return ctx.mul_accurately(factors)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ctx = <mpmath.ctx_mp.MPContext object at 0x7f61e91cbef0>, factors = <function qp.<locals>.factors at 0x7f61e6a7b1e0>, check_step = 1

    def mul_accurately(ctx, factors, check_step=1):
        prec = ctx.prec
        try:
            extraprec = 10
            while 1:
                ctx.prec = prec + extraprec + 5
                max_mag = ctx.ninf
                one = ctx.one
                s = one
                k = 0
>               for factor in factors():
E               RuntimeError: generator raised StopIteration

mpmath/ctx_base.py:391: RuntimeError
========================================================== warnings summary ==========================================================
/usr/lib/python3.7/site-packages/_pytest/config/findpaths.py:42: RemovedInPytest4Warning: [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
  config=config,

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/libmp/libelefun.py:203: DeprecationWarning: invalid escape sequence \ 
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/libmp/gammazeta.py:389: DeprecationWarning: invalid escape sequence \ 
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/libmp/gammazeta.py:861: DeprecationWarning: invalid escape sequence \ 
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/libmp/gammazeta.py:1104: DeprecationWarning: invalid escape sequence \ 
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/calculus/extrapolation.py:815: DeprecationWarning: invalid escape sequence \s
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/calculus/quadrature.py:407: DeprecationWarning: invalid escape sequence \c
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/calculus/quadrature.py:413: DeprecationWarning: invalid escape sequence \c
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/identification.py:744: DeprecationWarning: invalid escape sequence \s
  """

/var/tmp/portage/dev-python/mpmath-1.0.0-r1/work/mpmath-1.0.0/mpmath/ctx_mp.py:524: DeprecationWarning: invalid escape sequence \s
  """

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================== 2 failed, 459 passed, 1 skipped, 10 warnings in 110.31 seconds ===================================

**Comment by skirpichev** [comment]
@grozin, did you check the development version (just pip install from the mpmath's git repo)?

See #398 and more recent merged pull requests.  I believe, this issue was fixed recently and there are CI tests for CPython 3.7, which pass now for the master branch: see [here](https://travis-ci.org/fredrik-johansson/mpmath).

@fredrik-johansson, maybe you can release a new version?  (BTW, I would like to see also solution for #401 with new release.)

**Comment by warnerjon12** [comment]
> @fredrik-johansson, maybe you can release a new version? (BTW, I would like to see also solution for #401 with new release.)

This is now done on my branch, pull request in

**Comment by fredrik-johansson** [comment]
Yes there will certainly be a new release soon when the current round of PRs and major open issues have been dealt with!

**Comment by fredrik-johansson** [comment]
Are there any issues left that people strongly want to see fixed before the new release?
