### ISSUE TITLE
mpmath.mpf constructor wrongly works with finf/fninf

### ISSUE THREAD

**Issue by skirpichev** [fredrik-johansson/mpmath#438]
With GMPY:
```python
>>> import mpmath
>>> mpmath.mpf(mpmath.libmp.finf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 72, in __new__
    v._mpf_ = normalize(sign, MPZ(man), exp, bc, prec, rounding)
TypeError: arguments long, MPZ_Object*, PyObject*, long, long, char needed
>>> mpmath.mpf(mpmath.libmp.fninf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 72, in __new__
    v._mpf_ = normalize(sign, MPZ(man), exp, bc, prec, rounding)
TypeError: arguments long, MPZ_Object*, PyObject*, long, long, char needed
```

Without I got 0:
```python
>>> import mpmath
>>> mpmath.mpf(mpmath.libmp.finf)
mpf('0.0')
```

**Comment by skirpichev** [comment]
Oh, it's a very ancient issue, which was "fixed" [by sympy](https://github.com/sympy/sympy/issues/6639)...
