### ISSUE TITLE
gammainc(3, 0, -0.1) recursion error

### ISSUE THREAD

**Issue by ethankward** [fredrik-johansson/mpmath#467]
```
>>> from mpmath import
>>> gammainc(3, 0, -0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/expintegrals.py", line 163, in gammainc
    return -ctx.gammainc(z, b, a, regularized)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/expintegrals.py", line 166, in gammainc
    return +ctx._gamma3(z, a, b, regularized)
...
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/expintegrals.py", line 234, in _gamma3
    T1 = ctx.gammainc(z, a, regularized=regularized)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/expintegrals.py", line 162, in gammainc
    if ctx.re(a) > ctx.re(b):
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_mp_python.py", line 178, in __gt__
    def __gt__(s, t): return s._cmp(t, mpf_gt)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_mp_python.py", line 174, in _cmp
    return func(s._mpf_, t)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/libmp/libmpf.py", line 639, in mpf_gt
    return mpf_cmp(s, t) > 0
  File "/usr/local/lib/python3.6/dist-packages/mpmath/libmp/libmpf.py", line 586, in mpf_cmp
    if s == fzero: return -mpf_sign(t)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by regevs** [comment]
I also encountered this.
