### ISSUE TITLE
findroot failure on Python3

### ISSUE THREAD

**Issue by dimpase** [fredrik-johansson/mpmath#503]
on "pure" sage 9.0 python3: (mpmath 1.1.0), x86_64:
```
>>> import mpmath
>>> mpmath.mp.prec = 1000 #on 700 all is ok
>>> mpmath.findroot(lambda x: x**2 - 3, 2) # must use ** for exponentiation - pure Python
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sage/libs/mpmath/ext_main.pyx", line 1690, in
sage.libs.mpmath.ext_main.mpf_base.__repr__
(build/cythonized/sage/libs/mpmath/ext_main.c:21294)
  File "/home/scratch2/dimpase/sage/sage/local/lib/python3.7/site-packages/mpmath/libmp/libmpf.py",
line 1242, in to_str
    sign, digits, exponent = to_digits_exp(s, dps+3)
  File "/home/scratch2/dimpase/sage/sage/local/lib/python3.7/site-packages/mpmath/libmp/libmpf.py",
line 1200, in to_digits_exp
    digits = numeral(sd, base=10, size=dps)
  File "/home/scratch2/dimpase/sage/sage/local/lib/python3.7/site-packages/mpmath/libmp/libintmath.py",
line 158, in numeral_python
    A, B = divmod(n, base**half)
```

**Comment by dimpase** [comment]
However, I cannot reproduce it on (system) Python 3.7.3 in Debian buster, so this seems to be related to the way Sage builds mpmath.

**Comment by nouret** [comment]
I think here must be `A,B = n // (base**half), n % (base**half)`

**Comment by soehms** [comment]
> However, I cannot reproduce it on (system) Python 3.7.3 in Debian buster, so this seems to be related to the way Sage builds mpmath.

Indeed, it is a bug in Sage caused by the fact that mpmath behaves different when used inside Sage. I've pushed a fix in [Trac ticket #29009](https://trac.sagemath.org/29009).

**Comment by soehms** [comment]
Since the Trac ticket has positive review, right now, I think this one can be closed!

**Comment by dimpase** [comment]
OK
