### ISSUE TITLE
betainc fails when x1=0

### ISSUE THREAD

**Issue by naveensaigit** [fredrik-johansson/mpmath#567]
`betainc` fails when `x1=0` for some values of `a` and `b`. Surprisingly, setting `x2=0` makes it work. So, a workaround would be to use `-betainc(a, b, x2, x1)` instead of `betainc(a, b, x1, x2)`.
``` python
>>> from mpmath import betainc
>>> betainc(1, 2, 0, 5)
mpf('-7.5')
>>> betainc(1, 2, 5, 0)
mpf('7.5') #correct
>>> betainc(0, 0, 5, 0)
mpc(real='-4.6116860184273879e+18', imag='3.1415926535897931')
>>> betainc(0, 0, 0, 5) #fails here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpmath\ctx_mp_python.py", line 1035, in f_wrapped
    retval = f(ctx, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpmath\functions\expintegrals.py", line 116, in betainc
    v = x2**a * ctx.hyp2f1(a, 1-b, a+1, x2) / a
  File "<string>", line 7, in __div__
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpmath\libmp\libmpf.py", line 960, in mpf_div
    raise ZeroDivisionError
ZeroDivisionError
```
Ran into this while implementing Incomplete beta functions in SymPy [#20569](https://github.com/sympy/sympy/pull/20569#issuecomment-760111425)

**Comment by WarrenWeckesser** [comment]
Note that this result:

```
>>> betainc(0, 0, 5, 0)
mpc(real='-4.6116860184273879e+18', imag='3.1415926535897931')
```

is not correct.  If `x1` or `x2` is 0, `betainc(a, b, x1, x2)` has a pole at `a = 0`, so both `betainc(0, 0, 5, 0)` and `betainc(0, 0, 0, 5)` should probably raise a `ValueError`, analogous to the `ValueError` raised by `gamma(0)`:

```
In [13]: mp.gamma(0)
[✂✂✂ snip ✂✂✂]
ValueError: gamma function pole
```

By the symmetry relation `betainc(a, b, x1, x2) == betainc(b, a, 1 - x2, 1 - x1)`, if `x1` or `x2` is 1, `betainc(a, b, x1, x2)` has a pole at `b = 0`.  In `mpmath` 1.4.1, we get an assortment of `inf`-like or `nan`-like values; the exact value depends on the other parameters:

```
In [116]: mp.betainc(0.5, 0, 0.25, 1)  # b = 0, x2 = 1
Out[116]: mpf('inf')

In [117]: mp.betainc(0.5, 0, 0.25, 1+0j)  # b = 0, x2 = 1
Out[117]: mpc(real='inf', imag='nan')

In [118]: mp.betainc(0.5, 0, 0.25j, 1)  # b = 0, x2 = 1
Out[118]: mpc(real='inf', imag='-0.7559694104239076945094498785')

In [119]: mp.betainc(0.5-1j, 0, 0.25, 1)  # b = 0, x2 = 1
Out[119]: mpc(real='nan', imag='nan')
```

But that might be better as a `ValueError` (pole error), too.

Wolfram uses the "value" `ComplexInfinity` (which is not the same as `Infinity`):

```
In[66]:= Beta[0, 0, 3]  (* z=0, a=0, b=3 *)                                     

Out[66]= ComplexInfinity
```

I can submit a PR with a fix.  Either the function should raise a `ValueError` at the poles, or return something `inf`-like.  I lean towards `ValueError` (consistency with `gamma(0)` mentioned earlier), but an `inf`-like result is also possible.

**Comment by skirpichev** [comment]
> I can submit a PR with a fix.

Feel free to do so.

> Either the function should raise a ValueError at the poles, or return something inf-like. I lean towards ValueError (consistency with gamma(0) mentioned earlier), but an inf-like result is also possible.

Unfortunately, mpmath is inconsistent here.  ValueError looks better than some infinity.  Currently we have no concept of Mathematica-like ComplexInfinity, rather few variants of DirectedInfinity (e.g. inf or inf+infj).  See #148.
