### ISSUE TITLE
cannot build -- LookupError: setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by themaddoctor** [fredrik-johansson/mpmath#598]
```
$ tar -xf mpmath-1.2.0.tar.gz
$ cd mpmath-1.2.0
$ python3 setup.py install --root="$PWD/../build"
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setuptools.setup(use_scm_version=True)
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/mnt/quadrupole/sources/math/mpmath-1.2.0/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/integration.py", line 24, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/mnt/quadrupole/sources/math/mpmath-1.2.0/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
    parsed_version = _do_parse(config)
  File "/mnt/quadrupole/sources/math/mpmath-1.2.0/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 142, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/mnt/quadrupole/sources/math/mpmath-1.2.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by skirpichev** [comment]
Can you reproduce the problem on the current master branch?  mpmath master doesn't uses setuptools_scm.

**Comment by themaddoctor** [comment]
I found version 1.2.1, and all went well. Thanks.
