### ISSUE TITLE
appellf1 blows up and inaccurate 

### ISSUE THREAD

**Issue by dowkeruk** [fredrik-johansson/mpmath#633]
I am using mpmath because of its implementation of many hypergeometric functions but there seems to be a problem with appellf1 in that eg appellf1(1,1,1,4,1,1) should compute to 3 but an error of 'divide by zero' appears. It should reduce to hyp2f1(1,2,4,1). Also eg
appellf1(1,1,1,4,'0.9') computes to an inaccurate value in 30 secs while appellf1(1,1,1,4,'1.1') is fast and dps accurate. Mathematica has no problems. I am running mpmath in Jupyterlab and like the editor etc.

**Comment by skirpichev** [comment]
in the second and third examples I got:
```pycon
>>> appellf1(1,1,1,4,'1.1')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 1105, in f_wrapped
    retval = f(ctx, *args, **kwargs)
TypeError: appellf1() missing 1 required positional argument: 'y'
>>> 
```
